# Generated by Django 4.2.16 on 2024-10-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('handbook', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=5)),
                ('shortdescript', models.CharField(max_length=300)),
                ('page', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('handbook', models.CharField(max_length=50)),
                ('requisite', models.TextField(blank=True, max_length=5000)),
                ('required', models.TextField(blank=True, max_length=1000)),
                ('description', models.TextField()),
                ('special', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('edition', models.CharField(max_length=3, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(null=True)),
                ('handbook', models.CharField(max_length=20, null=True)),
                ('family', models.CharField(max_length=30, null=True)),
                ('slot', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('link', models.URLField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('handbook', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Edition', models.CharField(max_length=5)),
                ('handbook', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=500, null=True)),
                ('level', models.CharField(max_length=200)),
                ('casting_time', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('save_throw', models.CharField(max_length=10)),
                ('descript', models.TextField()),
                ('spellresistance', models.CharField(default='Yes', max_length=10)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        
    ]
