# Generated by Django 4.2.16 on 2024-10-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorites_spells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites_spells',
            name='name',
        ),
    ]
