# Generated by Django 4.2.16 on 2024-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_armor_classe_race_shield_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classSkills',
            field=models.CharField(default='-', max_length=1000),
            preserve_default=False,
        ),
    ]
