# Generated by Django 4.2.16 on 2024-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_classe_classskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=30)),
                ('atribute', models.CharField(max_length=3)),
                ('amorpenalty', models.BooleanField()),
                ('trained', models.BooleanField()),
                ('sinergy', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=20000)),
            ],
        ),
    ]
