# Generated by Django 4.2.16 on 2024-11-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_race_reach_alter_race_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='weapons',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
