# Generated by Django 4.2.16 on 2024-11-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_damage_weapons_damage_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='hands',
        ),
    ]
