# Generated by Django 4.2.16 on 2024-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_weapons_hands'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='amors_name',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='armors',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='weapons',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='weapons_name',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
