# Generated by Django 4.2.16 on 2024-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_classe_amors_name_classe_armors_classe_weapons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='designation',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
