# Generated by Django 4.2.16 on 2024-11-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_weapons_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='shields',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
