# Generated by Django 4.2.16 on 2024-11-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_classe_shields'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='book',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='gold',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='spells',
            field=models.CharField(default='-', max_length=2000),
            preserve_default=False,
        ),
    ]
