# Generated by Django 4.2.16 on 2024-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_classe_book_classe_gold_classe_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='key1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='key2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
