# Generated by Django 4.2.16 on 2024-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_race_key1_race_key2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='key1',
        ),
        migrations.RemoveField(
            model_name='race',
            name='key2',
        ),
        migrations.AddField(
            model_name='classe',
            name='key1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='key2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
