# Generated by Django 4.2.16 on 2024-11-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_race_key1_remove_race_key2_classe_key1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
