# Generated by Django 4.2.16 on 2024-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_classe_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magic_Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('slot', models.CharField(max_length=20)),
                ('book', models.CharField(max_length=100)),
                ('page', models.IntegerField(null=True)),
                ('caster_level', models.IntegerField()),
                ('aura', models.CharField(max_length=200, null=True)),
                ('activation', models.CharField(max_length=50, null=True)),
                ('sinergy', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('cost_create', models.CharField(max_length=50, null=True)),
                ('requirements', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
