# Generated by Django 4.2.16 on 2024-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_magic_enhancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic_enhancement',
            name='absolute_price',
            field=models.IntegerField(null=True),
        ),
    ]
