# Generated by Django 4.2.16 on 2024-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_magic_enhancement_absolute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shield',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
