# Generated by Django 4.2.16 on 2024-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_race_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbooks',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
