# Generated by Django 4.2.16 on 2024-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_handbooks_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ft',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
