# Generated by Django 4.2.16 on 2024-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_ft_alter_feats_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feats',
            name='page',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
