# Generated by Django 4.2.16 on 2024-11-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.CharField(max_length=20)),
                ('ca', models.IntegerField()),
                ('maxdex', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('penalty_speed', models.BooleanField()),
                ('category', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Race', models.CharField(max_length=50)),
                ('Adjustment', models.CharField(max_length=100)),
                ('SkillBonus', models.CharField(max_length=200)),
                ('Speed', models.IntegerField()),
                ('Size', models.CharField(max_length=10)),
                ('Space', models.IntegerField()),
                ('Reach', models.IntegerField()),
                ('Languages', models.CharField(max_length=100)),
                ('level_adjstument', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield', models.CharField(max_length=30)),
                ('ca', models.IntegerField()),
                ('maxdex', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=10)),
                ('critical', models.CharField(max_length=10)),
                ('reach', models.IntegerField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('hands', models.FloatField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
