# Generated by Django 4.2.16 on 2024-11-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_armor_races_shield_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='traits',
            field=models.TextField(default='-', max_length=5000),
            preserve_default=False,
        ),
    ]
