# Generated by Django 4.2.16 on 2024-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0004_delete_armor_delete_classes_delete_races_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('Poor', models.IntegerField()),
                ('Medium', models.IntegerField()),
                ('Good', models.IntegerField()),
            ],
        ),
    ]
