# Generated by Django 4.2.16 on 2024-11-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('Wealth', models.CharField(max_length=500)),
            ],
        ),
    ]
