# Generated by Django 4.2.16 on 2024-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_wealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(max_length=15)),
                ('medium', models.CharField(max_length=15)),
                ('heavy', models.CharField(max_length=15)),
            ],
        ),
    ]
